export const GENRE_OPTIONS = [
  { label: 'Alternative', value: 'Alternative' },
  { label: 'Ambient', value: 'Ambient' },
  { label: 'Bluegrass', value: 'Bluegrass' },
  { label: 'Blues', value: 'Blues' },
  { label: 'Classical', value: 'Classical' },
  { label: 'Country', value: 'Country' },
  { label: 'Dance Music', value: 'Dance Music' },
  { label: 'Disco', value: 'Disco' },
  { label: 'Drum And Bass', value: 'Drum And Bass' },
  { label: 'Dub Step', value: 'Dub Step' },
  { label: 'Easy Listening', value: 'Easy Listening' },
  { label: 'EDM', value: 'EDM' },
  { label: 'Experimental', value: 'Experimental' },
  { label: 'Folk', value: 'Folk' },
  { label: 'Funk', value: 'Funk' },
  { label: 'Gospel', value: 'Gospel' },
  { label: 'Grunge', value: 'Grunge' },
  { label: 'Heavy Metal', value: 'Heavy Metal' },
  { label: 'Hip Hop', value: 'Hip Hop' },
  { label: 'House', value: 'House' },
  { label: 'Indie Rock', value: 'Indie Rock' },
  { label: 'Industrial', value: 'Industrial' },
  { label: 'Inspirational', value: 'Inspirational' },
  { label: 'Instrumental', value: 'Instrumental' },
  { label: 'Jazz', value: 'Jazz' },
  { label: 'K-Pop', value: 'K-Pop' },
  { label: 'Latin', value: 'Latin' },
  { label: 'New Age', value: 'New Age' },
  { label: 'New Wave', value: 'New Wave' },
  { label: 'Pop', value: 'Pop' },
  { label: 'RnB', value: 'RnB' },
  { label: 'Reggae', value: 'Reggae' },
  { label: 'Rock', value: 'Rock' },
  { label: 'Ska', value: 'Ska' },
  { label: 'Soul', value: 'Soul' },
  { label: 'Techno', value: 'Techno' },
  { label: 'World Music', value: 'World Music' },
];
